<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class libros_seeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $faker = Faker::create();

        \DB::table('libros')->insert([
            'titulo' => "Harry Potter and the Philosopher's Stone.",
            'autor' => 'J. K. Rowling',
            'portada' => 'uploads/01.png',
            'enlace' => 'https://www.amazon.com/s?k=harry+potter+books&__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=32E5O23ZGJHXG&sprefix=harry+potter+b%2Caps%2C362&ref=nb_sb_ss_ts-doa-p_3_14',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Bloomsbury Publishing',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9780439362139',
            'fecha_publicacion' => '1997',
            'idioma' => "English",
            'valoracion' => '4',
            'apa' => "Rowling, J. K., author. (1998). Harry Potter and the Philosopher s Stone. New York :Arthur A. Levine Books.",
            'formato' => 'PDF',
            'paginas' => 240,
            'created_at' => date('Y-m-d H:m:s'),
            'updated_at' => date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
        ]);


        \DB::table('libros')->insert([
            'titulo' => "Harry Potter and the Chamber of Secrets.",
            'autor' => 'J. K. Rowling',
            'portada' => 'uploads/02.png',
            'enlace' => 'https://www.amazon.com/s?k=harry+potter+books&__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=32E5O23ZGJHXG&sprefix=harry+potter+b%2Caps%2C362&ref=nb_sb_ss_ts-doa-p_3_14',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Scholastic Corporation',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9780439420105',
            'fecha_publicacion' => '1998',
            'idioma' => "Spanish",
            'valoracion' => '4',
            'apa' => "Rowling, J. K., author. (1998). Harry Potter and the Chamber of Secrets. New York :Arthur A. Levine Books.",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 251,
            'formato' => 'PDF'
        ]);

        \DB::table('libros')->insert([
            'titulo' => "Harry Potter and the Prisoner of Azkaban.",
            'autor' => 'J. K. Rowling',
            'portada' => 'uploads/03.png',
            'enlace' => 'https://www.amazon.com/s?k=harry+potter+books&__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=32E5O23ZGJHXG&sprefix=harry+potter+b%2Caps%2C362&ref=nb_sb_ss_ts-doa-p_3_14',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Bloomsbury Publishing',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9780545582933',
            'fecha_publicacion' => '1999',
            'idioma' => "Spanish",
            'valoracion' => '4',
            'apa' => "Rowling, J. K., author. (1998). Harry Potter and the Prisoner of Azkaban. New York :Arthur A. Levine Books.",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 317,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Harry Potter and the Goblet of Fire.",
            'autor' => 'J. K. Rowling',
            'portada' => 'uploads/04.png',
            'enlace' => 'https://www.amazon.com/s?k=harry+potter+books&__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=32E5O23ZGJHXG&sprefix=harry+potter+b%2Caps%2C362&ref=nb_sb_ss_ts-doa-p_3_14',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Bloomsbury Publishing',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9781338299175',
            'fecha_publicacion' => '2000',
            'idioma' => "Spanish",
            'valoracion' => '5',
            'apa' => "Rowling, J. K., author. (1998). Harry Potter and the Goblet of Fire. New York :Arthur A. Levine Books.",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 636,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Harry Potter and the Order of the Phoenix.",
            'autor' => 'J. K. Rowling',
            'portada' => 'uploads/05.png',
            'enlace' => 'https://www.amazon.com/s?k=harry+potter+books&__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=32E5O23ZGJHXG&sprefix=harry+potter+b%2Caps%2C362&ref=nb_sb_ss_ts-doa-p_3_14',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Scholastic Corporation',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9780545582971',
            'fecha_publicacion' => '2003',
            'idioma' => "English",
            'valoracion' => '5',
            'apa' => "Rowling, J. K., author. (1998). Harry Potter and the Order of the Phoenix. New York :Arthur A. Levine Books.",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 901,
            'formato' => 'PDF'
        ]);

        \DB::table('libros')->insert([
            'titulo' => "Harry Potter and the Half-Blood Prince.",
            'autor' => 'J. K. Rowling',
            'portada' => 'uploads/06.png',
            'enlace' => 'https://www.amazon.com/s?k=harry+potter+books&__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=32E5O23ZGJHXG&sprefix=harry+potter+b%2Caps%2C362&ref=nb_sb_ss_ts-doa-p_3_14',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Scholastic Corporation',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9780439785969',
            'fecha_publicacion' => '2005',
            'idioma' => "English",
            'valoracion' => '5',
            'apa' => "Rowling, J. K., author. (1998). Harry Potter and the Half-Blood Prince. New York :Arthur A. Levine Books.",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 607,
            'formato' => 'PDF'
        ]);

        \DB::table('libros')->insert([
            'titulo' => "Harry Potter and the Deathly Hallows.",
            'autor' => 'J. K. Rowling',
            'portada' => 'uploads/07.png',
            'enlace' => 'https://www.amazon.com/s?k=harry+potter+books&__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=32E5O23ZGJHXG&sprefix=harry+potter+b%2Caps%2C362&ref=nb_sb_ss_ts-doa-p_3_14',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Scholastic Corporation',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9781644732137',
            'fecha_publicacion' => '2007',
            'idioma' => "English",
            'valoracion' => '5',
            'apa' => "Rowling, J. K., author. (1998). Harry Potter and the Deathly Hallows. New York :Arthur A. Levine Books.",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 607,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "The Fellowship of the Ring.",
            'autor' => 'J. R. R. Tolkien',
            'portada' => 'uploads/08.png',
            'enlace' => 'https://www.amazon.com/-/es/J-R-R-Tolkien/dp/0358653037/ref=sr_1_3?__mk_es_US=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=Z1PUUIX03G6K&keywords=lord+of+the+rings+books&qid=1638916358&sprefix=lord+of+the+rings+books%2Caps%2C352&sr=8-3',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Scholastic Corporation',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9780261102385',
            'fecha_publicacion' => '1954',
            'idioma' => "English",
            'valoracion' => '5',
            'apa' => "Tolkien, J. R. R. 1991. The Lord of the Rings. London, England: HarperCollins..",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 423,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Your Erroneous Zones",
            'autor' => 'Wayne Dyer',
            'portada' => 'uploads/09.png',
            'enlace' => 'libros/tus_zonas_erroneas.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Random House Mondadori',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788497593939',
            'fecha_publicacion' => '2003',
            'idioma' => "English",
            'valoracion' => '3',
            'apa' => "Dyer, W. W. (2003). Tus zonas erróneas. Ciudad Autónoma de Buenos Aires, Argentina: Mondadori",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 2,
            'paginas' => 320,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El poder del ahora",
            'autor' => 'Eckhart Tolle',
            'portada' => 'uploads/10.png',
            'enlace' => 'libros/el_poder_del_ahora.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Grijalbo',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789502805924',
            'fecha_publicacion' => '2012',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Tolle, E. (2012). El poder del ahora. Ciudad Autónoma de Buenos Aires, Argentina: Grijalbo",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 2,
            'paginas' => 256,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El arte de no amargarse la vida",
            'autor' => 'Rafael Santandreu',
            'portada' => 'uploads/11.png',
            'enlace' => 'libros/el_arte_de_no_amargarse.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Oniro',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-987-22673-3-9',
            'fecha_publicacion' => '2012',
            'idioma' => "Español",
            'valoracion' => '3',
            'apa' => "Tolle, E. (2012). El poder del ahora. Ciudad Autónoma de Buenos Aires, Argentina: Grijalbo",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 2,
            'paginas' => 240,
            'formato' => 'PDF'
        ]);

        \DB::table('libros')->insert([
            'titulo' => "El poder de confiar en ti",
            'autor' => 'Curro Cañete',
            'portada' => 'uploads/12.png',
            'enlace' => 'libros/el_poder_de_confiar_en_ti.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Planeta',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-987-22673-3-9',
            'fecha_publicacion' => '2019',
            'idioma' => "Español",
            'valoracion' => '3',
            'apa' => "El poder de confiar en ti. Aprende a tener fe en ti y conseguirás lo que quieras, 2019",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 2,
            'paginas' => 256,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Cómo ganar amigos e influir sobre las personas",
            'autor' => 'Dale Carnegie',
            'portada' => 'uploads/13.png',
            'enlace' => 'libros/como_ganar_amigos_e_influir_sobre_las_personas.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Sudamericana',
            'edicion' => $faker->randomDigit(),
            'isbn' => '950-07-2712-9',
            'fecha_publicacion' => '2008',
            'idioma' => "Español",
            'valoracion' => '3',
            'apa' => "Carnegie, D. (2008). Cómo ganar amigos e influir sobre las personas. Ciudad Autónoma de Buenos Aires, Argentina: Sudamericana",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 2,
            'paginas' => 304,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El monje que vendió su Ferrari",
            'autor' => 'Robin Sharma',
            'portada' => 'uploads/14.png',
            'enlace' => 'libros/el_monje_que_vendio_su_ferrari.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Sudamericana',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-950-07-4766-0',
            'fecha_publicacion' => '2015',
            'idioma' => "Español",
            'valoracion' => '3',
            'apa' => "Sharma, R. (2015). El monje que vendió su Ferrari. Ciudad Autónoma de Buenos Aires, Argentina: Sudamericana",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 2,
            'paginas' => 224,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Cómo hacer que te pasen cosas buenas",
            'autor' => 'Marian Rojas Estapé',
            'portada' => 'uploads/15.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Espasa',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-84-670-5330-2',
            'fecha_publicacion' => '2018',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Marian Rojas Estapé. (2018).Cómo hacer que te pasen cosas buenas . Ciudad Autónoma de Buenos Aires, Argentina: Espasa",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 2,
            'paginas' => 232,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Asesinato en el Orient Express",
            'autor' => 'Agatha Christie',
            'portada' => 'uploads/16.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Espasa',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-84-670-4541-3',
            'fecha_publicacion' => '2015',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Agatha Christie. (2015).Asesinato en el Orient Express. Espasa",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 248,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "La Verdad Sobre El Caso Harry Quebert",
            'autor' => 'Dicker Joel',
            'portada' => 'uploads/17.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'DEBOLSILLO',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789877252231',
            'fecha_publicacion' => '2017',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Dicker Joel. (2017).La Verdad Sobre El Caso Harry Quebert. DEBOLSILLO",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 800,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Reina Roja",
            'autor' => 'Juan Gomez-Jurado',
            'portada' => 'uploads/18.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Ediciones B',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788466664417',
            'fecha_publicacion' => '2018',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Juan Gomez-Jurado. (2018).Reina Roja, Ediciones B",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 568,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "La Sombra del Viento",
            'autor' => 'Carlos Ruiz Zafón',
            'portada' => 'uploads/19.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Planeta',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-84-08-09264-3',
            'fecha_publicacion' => '2002',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Carlos Ruiz Zafón. (2002).La Sombra del Viento. Planeta",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 576,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El silencio de la ciudad blanca",
            'autor' => 'Eva García Sáenz de Urturi',
            'portada' => 'uploads/20.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Editorial Planeta',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-84-08-15416-7',
            'fecha_publicacion' => '2022',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Eva García Sáenz de Urturi. (2022).El silencio de la ciudad blanca. Editorial Planeta",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 480,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El sabueso de los Baskerville",
            'autor' => 'Arthur Conan Doyle',
            'portada' => 'uploads/21.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Gradifco',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-987-1093-05-2',
            'fecha_publicacion' => '2007',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Doyle, A. C. (2007). El sabueso de los Baskerville. Caseros, Argentina: Gradifco",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 192,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Perdida ",
            'autor' => 'Gyllian Flynn ',
            'portada' => 'uploads/22.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Mondadori',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9783596188789',
            'fecha_publicacion' => '2014',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Gyllian Flynn . (2014). Perdida . Caseros, Argentina: Mondadori",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 592,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Te veré bajo el hielo",
            'autor' => 'Robert Bryndza',
            'portada' => 'uploads/23.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Roca Bolsillo',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788416240937',
            'fecha_publicacion' => '2018',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Robert Bryndza. (2018). Te veré bajo el hielo . Roca Bolsillo",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 400,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El espía que surgió del frío",
            'autor' => 'John le Carré',
            'portada' => 'uploads/24.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Editorial Planeta',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-84-08-20453-4',
            'fecha_publicacion' => '2002',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "John le Carré. (2002). El espía que surgió del frío. Editorial Planeta",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 366,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "La princesa de hielo",
            'autor' => 'Camilla Lackberg',
            'portada' => 'uploads/25.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'OCEANO EXPRES',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9786075275512',
            'fecha_publicacion' => '2008',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Camilla Lackberg. (2008). La princesa de hielo. OCEANO EXPRES",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 415,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Inferno",
            'autor' => 'Dan Brown',
            'portada' => 'uploads/26.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Booket',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-987-580-698-6',
            'fecha_publicacion' => '2014',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Dan Brown. (2014). Inferno. Booket",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 560,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "La chica del tren",
            'autor' => 'Paula Hawkins',
            'portada' => 'uploads/27.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Booket',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-84-08-19302-9',
            'fecha_publicacion' => '2018',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Paula Hawkins. (2018). La chica del tren. Booket",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 496,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Las aventuras de Sherlock Holmes",
            'autor' => 'Conan Doyle Arthur',
            'portada' => 'uploads/28.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'ALMA',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788415618829',
            'fecha_publicacion' => '2018',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Conan Doyle Arthur. (2018).Las aventuras de Sherlock Holmes. ALMA",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 12,
            'paginas' => 368,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "La metáfora en el arte",
            'autor' => 'Oliveras Elena',
            'portada' => 'uploads/29.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'PAIDOS',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789501203332',
            'fecha_publicacion' => '2021',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Oliveras Elena. (2021)La metáfora en el arte. PAIDOS",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 1,
            'paginas' => 304,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "La historia del arte",
            'autor' => 'E. H. Gombrich',
            'portada' => 'uploads/30.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Phaidon',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9780714898704',
            'fecha_publicacion' => '2007',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "E. H. Gombrich. (2007). La historia del arte. Phaidon",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 1,
            'paginas' => 688,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Las vidas de los más excelentes arquitectos, pintores y escultores italianos",
            'autor' => 'Giorgio Vasari',
            'portada' => 'uploads/31.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Phaidon',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788437627366',
            'fecha_publicacion' => '2011',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Giorgio Vasari. (2011). Las vidas de los más excelentes arquitectos, pintores y escultores italianos. Phaidon",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 1,
            'paginas' => 872,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Otra historia del arte: No pasa nada si no te gustas Las Meninas",
            'autor' => 'Miguel Ángel Cajigal Vera',
            'portada' => 'uploads/32.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Plan B',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788418051258',
            'fecha_publicacion' => '2021',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Miguel Ángel Cajigal Vera. (2021). Otra historia del arte: No pasa nada si no te gustas Las Meninas. Plan B",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 1,
            'paginas' => 240,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El hijo del Capitán Trueno",
            'autor' => 'Miguel Bosé',
            'portada' => 'uploads/33.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Plan B',
            'edicion' => $faker->randomDigit(),
            'isbn' => '978-950-852-332-7',
            'fecha_publicacion' => '2021',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Miguel Bosé. (2021). El hijo del Capitán Trueno. Plan B",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 3,
            'paginas' => 664,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Gabo y Mercedes: una despedida",
            'autor' => 'Rodrigo García',
            'portada' => 'uploads/34.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Penguin Random House',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789585581593',
            'fecha_publicacion' => '2021',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Rodrigo García. (2021). Gabo y Mercedes: una despedida. Penguin Random House",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 3,
            'paginas' => 120,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "La bailarina de Auschwitz",
            'autor' => 'Edith Eger',
            'portada' => 'uploads/35.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Planeta',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788408202400',
            'fecha_publicacion' => '2019',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Edith Eger. (2019).La bailarina de Auschwitz: Una inspiradora historia de valentía y supervivencia. Planeta",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 3,
            'paginas' => 416,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "The storyteller tales of life and music",
            'autor' => 'Dave Grohl',
            'portada' => 'uploads/36.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Harper Collins',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9780063076099',
            'fecha_publicacion' => '2019',
            'idioma' => "Español",
            'valoracion' => '3',
            'apa' => "Dave Grohl. (2019).The storyteller tales of life and music. Harper Collins",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 3,
            'paginas' => 384,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Yo, el Rey",
            'autor' => 'Pilar Eyre',
            'portada' => 'uploads/37.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'La Esfera De Los Libros',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788491649496',
            'fecha_publicacion' => '2020',
            'idioma' => "Español",
            'valoracion' => '4',
            'apa' => "Pilar Eyre. (2020).Yo, el Rey. La Esfera De Los Libros",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 3,
            'paginas' => 544,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Diario de Ana Frank",
            'autor' => 'Anne Frank',
            'portada' => 'uploads/38.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Unilit',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789807875042',
            'fecha_publicacion' => '2018',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Anne Frank. (2018).Diario de Ana Frank. Unilit",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 3,
            'paginas' => 189,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "J. R. R. Tolkien. Una Biografía",
            'autor' => 'Humphrey Carpenter ',
            'portada' => 'uploads/39.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Planeta ',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9783608934311',
            'fecha_publicacion' => '2002 ',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Humphrey Carpenter . (2002 ).J. R. R. Tolkien. Una Biografía. Planeta",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 3,
            'paginas' => 295,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El gen egoísta",
            'autor' => 'Richard Dawkins',
            'portada' => 'uploads/40.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Editorial Bruño',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788469620434',
            'fecha_publicacion' => '2017',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Richard Dawkins. (2017).El gen egoísta. Editorial Bruño",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 4,
            'paginas' => 636,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Primavera Silenciosa",
            'autor' => 'Rachel L. Carson',
            'portada' => 'uploads/41.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Editorial Crítica',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788416771172',
            'fecha_publicacion' => '2016',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Rachel L. Carson. (2016).Primavera Silenciosa. Editorial Crítica",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 4,
            'paginas' => 416,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Frankenstein o el Moderno Prometeo",
            'autor' => 'Shelley Mary',
            'portada' => 'uploads/42.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Estacion Mandioca',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9871652070',
            'fecha_publicacion' => '2000',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Shelley Mary. (2000).Frankenstein o el Moderno Prometeo. Estacion Mandioca",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 4,
            'paginas' => 128,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Sapiens: De animales a dioses",
            'autor' => 'Yuval Noah Harari',
            'portada' => 'uploads/43.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Debate',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788499926223',
            'fecha_publicacion' => '2015',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Yuval Noah Harari. (2015).Sapiens: De animales a dioses. Debate",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 4,
            'paginas' => 496,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Los dragones del Edén",
            'autor' => 'Carl Sagan',
            'portada' => 'uploads/44.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Debate',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9786077471813',
            'fecha_publicacion' => '2013',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Carl Sagan. (2013).Los dragones del Edén. Debate",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 4,
            'paginas' => 264,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Una breve historia de casi todo",
            'autor' => 'Bill Bryson',
            'portada' => 'uploads/45.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Rba Bolsillo',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788492966790',
            'fecha_publicacion' => '2016',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Bill Bryson. (2016).Una breve historia de casi todo. Rba Bolsillo",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 4,
            'paginas' => 640,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El origen de las especies",
            'autor' => 'Charles Darwin',
            'portada' => 'uploads/46.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Gradifco',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789871093694',
            'fecha_publicacion' => '2016',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Charles Darwin. (2016).El origen de las especies. Gradifco",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 4,
            'paginas' => 271,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Marte azul",
            'autor' => 'Kim Stanley Robinson',
            'portada' => 'uploads/47.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Booket',
            'edicion' => $faker->randomDigit(),
            'isbn' => '8445001825',
            'fecha_publicacion' => '2014',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Kim Stanley Robinson. (2014).Marte azul. Booket",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 736,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Hyperion",
            'autor' => 'Dan Simmons',
            'portada' => 'uploads/48.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Ediciones B',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788466658034',
            'fecha_publicacion' => '2015',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Dan Simmons. (2015).Hyperion. Ediciones B",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 648,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Guía del autoestopista galáctico",
            'autor' => 'Douglas Adams',
            'portada' => 'uploads/49.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Anagrama',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788433973108',
            'fecha_publicacion' => '2007',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Douglas Adams. (2007).Guía del autoestopista galáctico. Anagrama",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 296,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El marciano",
            'autor' => 'Andy Weir',
            'portada' => 'uploads/50.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Ediciones B',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788466655057',
            'fecha_publicacion' => '2014',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Andy Weir. (2014).El marciano. Ediciones B",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 408,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Trilogía de la Fundación",
            'autor' => 'Isaac Asimov',
            'portada' => 'uploads/51.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Debolsillo',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788499083209',
            'fecha_publicacion' => '2010',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Isaac Asimov. (2010).Trilogía de la Fundación. Debolsillo",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 904,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "La guerra de los mundos",
            'autor' => 'Herbert George Wells',
            'portada' => 'uploads/52.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Ediciones Brontes',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9788416827022',
            'fecha_publicacion' => '2016',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Herbert George Wells. (2016).La guerra de los mundos. Ediciones Brontes",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 160,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "1984",
            'autor' => 'George Orwell',
            'portada' => 'uploads/53.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Debolsillo',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789875669284',
            'fecha_publicacion' => '2013',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "George Orwell. (2013).1984.Debolsillo",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 352,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "Fahrenheit 451",
            'autor' => 'Bradbury, Ray',
            'portada' => 'uploads/54.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Minotauro',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789505472123',
            'fecha_publicacion' => '2020',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Bradbury, Ray. (2020).Fahrenheit 451.Minotauro",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 272,
            'formato' => 'PDF'
        ]);
        \DB::table('libros')->insert([
            'titulo' => "El mesías de Dune ",
            'autor' => 'Frank Herbert',
            'portada' => 'uploads/55.png',
            'enlace' => 'libros/default.pdf',
            'comentarios' => $faker->realText($maxNbChars = 200, $indexSize = 2),
            'editorial' => 'Debolsillo',
            'edicion' => $faker->randomDigit(),
            'isbn' => '9789877254396',
            'fecha_publicacion' => '2021',
            'idioma' => "Español",
            'valoracion' => '5',
            'apa' => "Bradbury, Ray. (2021).El mesías de Dune.Debolsillo",
            'created_at' =>date('Y-m-d H:m:s'),
            'updated_at' =>date('Y-m-d H:m:s'),
            'idUser' => $faker->numberBetween($min = 1, $max = 10),
            'idCategoria' => 5,
            'paginas' => 304,
            'formato' => 'PDF'
        ]);
    }
}

